processor:
  build: .
  links:
    - db
  env_file: .env
db:
  image: postgres:9.4.7
  ports:
    - 55432:5432
  environment:
    POSTGRES_USER: dataprocessor
    POSTGRES_DB: dataprocessor
    POSTGRES_PASSWORD: vip2016
